### ISSUE TITLE
Make an option to ignore one-time variables in template literals

### ISSUE THREAD

**Issue by jwbth** [Bas950/eslint-plugin-no-one-time-vars#11]
I love what this plugin does. However, in my code style, I allow one-time variables to be used in [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), e.g. I'd write
```js
const someNonTriviallyComputedVar = obj.namespace.method('param', { prop: value }) + ns.SOME_CONSTANT;
return `Some text that includes the variable; ${someNonTriviallyComputedVar}; some more text`;
```
rather than
```js
return `Some text that includes the variable; ${obj.namespace.method('param', { prop: value }) + ns.SOME_CONSTANT}; some more text`;
```
Simple text concatenation doesn't count – it's only about template literals. I propose to create an option to ignore such usage.

**Comment by Slowlife01** [comment]
Added

**Comment by jwbth** [comment]
That's great, thank you! Rushing to test it 🚀
