### ISSUE TITLE
Autofix for exported variables breaks code

### ISSUE THREAD

**Issue by jwbth** [Bas950/eslint-plugin-no-one-time-vars#12]
Setup:
```js
    {
      'no-one-time-vars/no-one-time-vars': [
        'warn',
        {
          ignoreExportedVariables: false,
        },
      ],
    },
```
Demonstration:
![Code_RDSNyBMBsy](https://github.com/Bas950/eslint-plugin-no-one-time-vars/assets/33615628/90f5ce8d-e304-4a77-a82b-29120dfe1812)

**Comment by jwbth** [comment]
Not sure what the autofix should be though, as this syntax is not allowed:
```js
export { obj: { prop: 'value' } };
```

Maybe adding `export ` to the beginning and removing `obj` from `export { obj };` (and the entire line since there are no more exports)?
```js
export const obj = { prop: 'value' };
```

Or just don't autofix.

**Comment by Slowlife01** [comment]
fixed in https://github.com/Bas950/eslint-plugin-no-one-time-vars/commit/b07249dcbcc1808034a3028a14f92b825e894af0

*only tested with simple cases*
