### ISSUE TITLE
Rule not triggered for unclear reasons

### ISSUE THREAD

**Issue by jwbth** [Bas950/eslint-plugin-no-one-time-vars#15]
This code doesn't trigger the rule (with default options):

```js
    const $result = $('<table>')
      .addClass('diff')
      .append(
        $('<colgroup>').append(
          $('<col>').addClass('diff-marker'),
          $('<col>').addClass('diff-content'),
          $('<col>').addClass('diff-marker'),
          $('<col>').addClass('diff-content'),
        ),
      )
      .append(body);
    this.renderCompare($result);
```

If I remove the part
```js
        $('<colgroup>').append(
          $('<col>').addClass('diff-marker'),
          $('<col>').addClass('diff-content'),
          $('<col>').addClass('diff-marker'),
          $('<col>').addClass('diff-content'),
        ),
```
it does trigger. Then again, if I add a couple of `.append()`s, it stops triggering. Basically, it seems to depend on some complexity measure where more complex code doesn't trigger the rule.

I would like to have the rule triggered regardless of the complexity or at least be able to set this as an option.

**Comment by jwbth** [comment]
It seemingly depends just on character count being less than 100, e.g. this does trigger
```js
$('<table>')
      .addClass('diff')
      .append()
      .append(bodybbbbbbbbbbbbbbbbbbbbbbbb)
```
(99 characters) while this doesn't:
```js
$('<table>')
      .addClass('diff')
      .append()
      .append(bodybbbbbbbbbbbbbbbbbbbbbbbbb)
```
(100 characters)

**Comment by jwbth** [comment]
Well yeah, it's this line:
https://github.com/Bas950/eslint-plugin-no-one-time-vars/blob/75b0ece946f0dd5207d454dcc266db96ebc90c10/lib/rules/no-one-time-vars.js#L149

So it's intentional.

My use case for this plugin is that I aim to make my code more functional-like. If there are e.g. too many nesting levels, I prefer to extract functions, not variables. So there are very few exceptions where I could use a variable only once. If a portion of my code is too long/complex for my liking, I'd likely notice it and refactor without the use of one-time variables, but until/unless that happens, I'd like `no-one-time-vars` to have no exceptions for complexity/length.

**Comment by Slowlife01** [comment]
Added as an option. 

We won't be maintaining the plugin as actively now, feel free to mess with the code and submit pull requests tho.
